[versions]
brv = "1.4.3"
com-android-application = "8.1.0"
glide = "4.15.1"
immersionbar = "3.2.2"
lottie = "6.1.0"
media3 = "1.1.0"
org-jetbrains-kotlin-android = "1.9.0"
material = "1.10.0-alpha05"
serialize = "3.0.1"
uiViewbinding = "1.4.3"
utilcodex = "1.31.1"
activity-compose = "1.8.0-alpha06"
xx-permissions = "18.2"
animation = "1.4.3"
material3 = "1.1.1"
recyclerview = "1.3.0"
appcompatResources = "1.6.1"
google-material = "1.9.0"

[libraries]
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "uiViewbinding" }
brv = { module = "com.github.liangjingkanji:BRV", version.ref = "brv" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
immersionbar = { module = "com.geyifeng.immersionbar:immersionbar", version.ref = "immersionbar" }
serialize = { module = "com.github.liangjingkanji:Serialize", version.ref = "serialize" }
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
xx-permissions = { module = "com.github.getActivity:XXPermissions", version.ref = "xx-permissions" }
androidx-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "animation" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-appcompat-resources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "appcompatResources" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }

[libraries.material]
group = "com.google.android.material"
name = "material"
version.ref = "material"

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-application" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }

[bundles]

