[versions]
brv = "1.4.1"
com-android-application = "8.2.0-alpha11"
glide = "4.15.1"
immersionbar = "3.2.2"
lottie = "6.0.1"
media3 = "1.1.0"
navigation-compose = "2.6.0"
org-jetbrains-kotlin-android = "1.8.22"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0-alpha05"
constraintlayout = "2.1.4"
serialize = "3.0.1"
tooltip = "1.2.2"
uiViewbinding = "1.4.3"
utilcodex = "1.31.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.06.01"
xx-permissions = "18.2"

[libraries]
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "uiViewbinding" }
brv = { module = "com.github.liangjingkanji:BRV", version.ref = "brv" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
immersionbar = { module = "com.geyifeng.immersionbar:immersionbar", version.ref = "immersionbar" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
serialize = { module = "com.github.liangjingkanji:Serialize", version.ref = "serialize" }
tooltip = { module = "com.github.liangjingkanji:Tooltip", version.ref = "tooltip" }
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
xx-permissions = { module = "com.github.getActivity:XXPermissions", version.ref = "xx-permissions" }
androidx-viewbinding = { group = "androidx.databinding", name = "viewbinding", version = "8.2.0-alpha11" }

[libraries.material]
group = "com.google.android.material"
name = "material"
version.ref = "material"


[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-application" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }

[bundles]

