name: Vyx CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'renovate.json'
      - 'crowdin.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'renovate.json'
      - 'crowdin.yml'
  workflow_dispatch:

jobs:
  Build:
    if: contains(github.event.head_commit.message, '[skip_ci]') == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          # cache: 'gradle'
          # check-latest: true

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > keystore.jks
          bash ./gradlew assemble
        env:
          KEYSTORE_PATH: "../keystore.jks"
          KEYSTORE_PASS: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          CANARY_BUILD: "true"

      - name: Find APK
        run: |
          echo "RELEASE_APK=$(find 'app/build/outputs/apk/release' -name '*.apk')" >> $GITHUB_ENV
          echo "DEBUG_APK=$(find 'app/build/outputs/apk/debug' -name '*.apk')" >> $GITHUB_ENV

      - name: Show Apks SHA256
        if: success()
        run: |
          echo "### Build Success" >> $GITHUB_STEP_SUMMARY
          echo "|Artifact|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:--------:|:----------|" >> $GITHUB_STEP_SUMMARY
          release=($(sha256sum ${{ env.RELEASE_APK }}))
          echo "|Release|$release" >> $GITHUB_STEP_SUMMARY
          debug=($(sha256sum ${{ env.DEBUG_APK }}))
          echo "|Debug|$debug" >> $GITHUB_STEP_SUMMARY

      - name: Upload Release Apk
        uses: actions/upload-artifact@v3
        with:
          name: VideoYouX-Release-${{ github.event.head_commit.id }}
          path: ${{ env.RELEASE_APK }}

      - name: Upload Debug Apk
        uses: actions/upload-artifact@v3
        with:
          name: VideoYouX-Debug-${{ github.event.head_commit.id }}
          path: ${{ env.DEBUG_APK }}

      - name: Post to Channel
        if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[skip_post]') == false
        env:
          CHANNEL_ID: ${{ secrets.TELEGRAM_TO }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          RELEASE: ${{ env.RELEASE_APK }}
          DEBUG: ${{ env.DEBUG_APK }}
          COMMIT_MESSAGE: |+
            GitHub New CI\
            
            `${{ github.event.head_commit.message }}`
            
            by `${{ github.event.head_commit.author.name }}`
            
            See commit detail [here](${{ github.event.head_commit.url }})
        run: |
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Frelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Fdebug%22%2C%22parse_mode%22%3A%22MarkdownV2%22%2C%22caption%22%3A${ESCAPED}%7D%5D"  -F release="@$RELEASE" -F debug="@$DEBUG"
