name: Android CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'corretto'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assemble

    - name: Sign Release APK
      if: success()
      id: sign_release_apk
      uses: r0adkll/sign-android-release@v1.0.4
      with:
        releaseDirectory: ./app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD  }}

    - name: Sign Debug APK
      if: success()
      id: sign_debug_apk
      uses: r0adkll/sign-android-release@v1.0.4
      with:
        releaseDirectory: ./app/build/outputs/apk/debug
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD  }}

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: VideoYouX_Release
        path: ${{steps.sign_release_apk.outputs.signedReleaseFile}}

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: VideoYouX_Debug
        path: ${{steps.sign_debug_apk.outputs.signedReleaseFile}}

    - name: Post to Channel
      if: github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '[skip post]') == false
      env:
          CHANNEL_ID: ${{ secrets.TELEGRAM_TO }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          RELEASE: ${{steps.sign_release_apk.outputs.signedReleaseFile}}
          DEBUG: ${{steps.sign_debug_apk.outputs.signedReleaseFile}}
          COMMIT_MESSAGE: |+
            GitHub New CI\
            
            `${{ github.event.head_commit.message }}`
            by `${{ github.event.head_commit.author.name }}`
            
            See commit detail [here](${{ github.event.head_commit.url }})
      run: |
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Frelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Fdebug%22%2C%22parse_mode%22%3A%22MarkdownV2%22%2C%22caption%22%3A${ESCAPED}%7D%5D"  -F release="@$RELEASE" -F debug="@$DEBUG"
